evals:
  file: './evals.config'
  0:
    workflow_id: "github.com/dockstore-testing/md5sum-checker"
    version_id: "develop"
    trs_id: "dockstore"
    workflow_type: "CWL"
    submission_type: "params"
  1:
    workflow_id: "github.com/dockstore-testing/md5sum-checker/wdl"
    version_id: "develop"
    trs_id: "dockstore"
    workflow_type: "WDL"
    submission_type: "params"

toolregistries:
  file: './toolregistries.config'
  dockstore:
    host: "dockstore.org:8443"
    auth:
    proto: "https"

workflowservices:
  file: './workflowservices.config'
  local:
    host: "0.0.0.0:8080"
    auth:
    auth_type: ""
    proto: "http"

orchestrator:
  file: '~/.orchestratorConfig'
  evals:
    0
    1
  toolregistries:
    "dockstore"
  workflowservices:
    "local"
